static:
  /etc/issue:
    content: "{{ os_name }}\nKernel {{ kernel_version }} on an {{ arch }}\n\n"
  /etc/hostname:
    content: "{{ hostname }}\n"
  /etc/hosts:
    content: |
      127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
      ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
      127.0.1.1   {{ hostname }}
  /etc/os-release:
    content: |
      NAME="CentOS Linux"
      VERSION="{{ version_id }} (Core)"
      ID="{{ os_id }}"
      ID_LIKE="rhel fedora"
      VERSION_ID="{{ version_id }}"
      PRETTY_NAME="CentOS Linux {{ version_id }} (Core)"
      ANSI_COLOR="0;31"
      CPE_NAME="cpe:/o:centos:centos:{{ version_id }}"
      HOME_URL="https://www.centos.org/"
      BUG_REPORT_URL="https://bugs.centos.org/"
  /etc/passwd:
    type: static
    source: "centos/root/etc/passwd.txt"
  /etc/group:
    source: "centos/root/etc/group"
  /etc/shadow:
    source: "centos/root/etc/shadow"
  /etc/shells:
    source: "centos/root/etc/shells"
  /etc/ssh/sshd_config:
    source: "centos/root/etc/ssh/sshd_config"
  /home/admin/.bashrc:
    source: "centos/root/home/admin/.bashrc"
  /root/.bashrc:
    source: "centos/root/root/.bashrc"
  /bin/**:
    source: "centos/root/bin/"
  /usr/bin/**:
    source: "centos/root/usr/bin/"
  /etc/**:
    source: "centos/root/etc/"
